Feature/js 3
itbgtk09/WebDadJSTask pull request #4
Opened 2021-05-20 12:59 UTC by itbgtk09

2021-05-24 09:01 UTC, DenisKalyanov requested changes

2021-05-24 09:15 UTC, DenisKalyanov requested changes

2021-05-24 09:15 UTC, DenisKalyanov commented on src/scripts/script.js
> +})
Я бы посоветовал обработать вариант, при закрытии страницы чтобы сбрасывались все таймИнтервалы.
Потому что ты закроешь страницу, а код может продолжить выполняться и загружать твой браузер. 

Когда мы закрываем страницы, мы должны обнулить/отключить все таймауты и интервалы.

2021-05-24 15:25 UTC, itbgtk09 commented on src/scripts/script.js
> +})
Они же и так отключаются? У меня же данные нигде и никак не сохраняются

2021-05-24 15:27 UTC, itbgtk09 commented on src/scripts/script.js
> +    } else if (+workTime.value !== 0 && workSeconds === 0) {
Потому что он удобней и быстрее) Да и в моем случае, нет разницы между ним и parseInt

2021-05-24 16:09 UTC, itbgtk09 commented on src/scripts/script.js
> +let timeToRelax;
ну тут тот случай, когда эти переменные будут глобальными

2021-05-25 08:30 UTC, DenisKalyanov requested changes

2021-05-25 08:30 UTC, DenisKalyanov commented on src/scripts/script.js
> +    settings.classList.toggle('hide')
что за класс hide? Не нашёл я такого

2021-05-25 08:30 UTC, DenisKalyanov commented on src/scripts/script.js
> +    settings.classList.remove('hide')
Давай пока удалим этот дополнительный функционал и сначала отточим саму работу таймера.
Тем самым сократим количество кода и упростим его понимание.

2021-05-25 08:30 UTC, DenisKalyanov commented on src/scripts/script.js
> +    if (workSeconds != 0) {
Почему ты начинаешь проверку с workSeconds. Стоит добавить вообще проверку есть ли workTime?
Больше он нуля или нет. И в зависимости от того есть ли он вообще или нет, запускать остальной код.

2021-05-25 08:51 UTC, itbgtk09 commented on src/scripts/script.js
> +    settings.classList.toggle('hide')
Он скрывает поля ввода времени, после нажатия на кнопку старт и не дают изменить эти поля во время работы

2021-05-25 08:58 UTC, itbgtk09 commented on src/scripts/script.js
> +    if (workSeconds != 0) {
else if (+workTime.value !== 0 && workSeconds === 0) вот тут проверяется workTime
Если не добавлять проверку то звук будет играть всегда, когда будет новая минута, тира 5:00(звук), 4:00(звук)

2021-05-26 09:51 UTC, DenisKalyanov commented on src/scripts/script.js
> +    intervalPomodoro = setInterval(pomodoroTimerFunc, 1000);
У тебя идёт каждый раз запуск функции pomodoroTimerFunc.
Внутри которой каждую секунду проверяются 3 условия:

```
if (workSeconds != 0) {
if (workSeconds === 0 && +workTime.value === 0) {
if (+relaxTime.value === 0 && breakSeconds === 0) {
```

Можно ли пересмотреть концепцию кода так, чтобы минимизировать кол-во выполнения кода каждую секунду?

2021-05-27 09:18 UTC, DenisKalyanov approved these changes

2021-05-27 14:28 UTC, merged